FROM rust:1.88.0-bookworm AS build
WORKDIR /src
COPY Cargo.toml Cargo.lock ./
COPY crates ./crates
RUN cargo build --locked --release -p proofstormd

FROM gcr.io/distroless/cc-debian12:nonroot
COPY --from=build /src/target/release/proofstormd /usr/local/bin/proofstormd
USER 65532:65532
ENTRYPOINT ["/usr/local/bin/proofstormd"]
