//! Human-readable labels; wire identifiers remain stable.
use proofstorm_core::{OperationKind, OperationPhase};

#[must_use]
pub const fn action_title(kind: OperationKind) -> &'static str {
    match kind {
        OperationKind::NodeStart => "Start node",
        OperationKind::NodeStop => "Stop node",
        OperationKind::NodeRestart => "Restart node",
        OperationKind::ComponentRestart => "Restart component",
        OperationKind::BootstrapLiquidity => "Fund channels",
        OperationKind::PeerConnect => "Connect peers",
        OperationKind::PeerDisconnect => "Disconnect peers",
        OperationKind::ChannelOpen => "Open channel",
        OperationKind::ChannelPolicySet => "Update channel policy",
        OperationKind::ChannelClose => "Close channel",
        OperationKind::ChannelForceClose => "Force-close channel",
        OperationKind::ChannelRebalance => "Rebalance channel",
        OperationKind::NetworkPartition => "Partition network",
        OperationKind::NetworkDelay => "Add network delay",
        OperationKind::NetworkLoss => "Add packet loss",
        OperationKind::NetworkHeal => "Restore network",
        OperationKind::WalletInitialize => "Initialize wallet",
        OperationKind::WalletBalance => "Check wallet balance",
        OperationKind::WalletFund => "Fund wallet",
        OperationKind::WalletInvoice => "Create invoice",
        OperationKind::WalletPay => "Pay invoice",
        OperationKind::WalletQuoteClaim => "Claim wallet quote",
        OperationKind::WalletMeltQuoteRefresh => "Refresh payment quote",
        OperationKind::WalletRoundTrip => "Test wallet round trip",
        OperationKind::ConservationOracle => "Check fund conservation",
        OperationKind::ReachabilityOracle => "Check connectivity",
        OperationKind::ComponentForensics => "Inspect component files",
        OperationKind::ComponentExecLive => "Run command",
        OperationKind::PrivateTransfer => "Transfer private data",
        OperationKind::ComponentLogs => "Read component logs",
        OperationKind::AuthenticationConformance => "Test authentication",
        OperationKind::AuthenticationProtectedSpend => "Test authenticated spend",
        OperationKind::AuthenticationReplay => "Test authentication replay",
    }
}
#[must_use]
pub const fn outcome_title(phase: OperationPhase) -> &'static str {
    match phase {
        OperationPhase::Pending => "Pending",
        OperationPhase::Running => "Running",
        OperationPhase::Succeeded => "Completed",
        OperationPhase::Failed => "Failed",
        OperationPhase::Cancelled => "Cancelled",
    }
}

/// Display names for MCP discovery and interfaces that refer to exact tool IDs.
#[must_use]
pub fn tool_title(name: &str) -> Option<&'static str> {
    Some(match name {
        "lab_up" => "Start lab",
        "environment_read" => "View environment",
        "lab_inspect" => "Inspect lab",
        "lab_exec" | "component_exec_live" => action_title(OperationKind::ComponentExecLive),
        "lab_sync" => "Collect results",
        "lab_finish" => "Finish lab",
        "workspace_read" => "View workspace",
        "catalog_list" => "Browse components",
        "catalog_entry_read" => "View component specification",
        "catalog_config_schema_read" => "View configuration fields",
        "candidate_build" => "Build candidate",
        "candidate_wait" => "Wait for build",
        "candidate_list" => "List builds",
        "candidate_cancel" => "Cancel build",
        "network_capabilities" => "View network controls",
        "lab_plan" => "Plan lab",
        "lab_apply" => "Apply lab plan",
        "lab_create" => "Create lab draft",
        "lab_recipe_create" => "Create lab from recipe",
        "lab_read" => "View lab configuration",
        "lab_edit" => "Edit lab",
        "component_add" => "Add component",
        "component_update" => "Update component",
        "component_remove" => "Remove component",
        "link_add" => "Add connection",
        "link_remove" => "Remove connection",
        "lab_clone" => "Clone lab",
        "lab_validate" => "Validate lab",
        "lab_diff" => "Compare lab configurations",
        "lab_publish" => "Publish lab configuration",
        "lab_materialize" => "Deploy lab",
        "lab_status" => "Check lab status",
        "lab_component_status_list" => "List component statuses",
        "lab_inventory_list" => "List lab resources",
        "lab_wait" => "Wait for lab",
        "lab_close" => "Close lab",
        "experiment_create" => "Create experiment",
        "experiment_read" => "View experiment",
        "experiment_close" => "Close experiment",
        "session_start" => "Start session",
        "session_read" => "View session",
        "session_finish" => "Finish session",
        "session_list" => "List sessions",
        "private_access_issue" => "Grant private access",
        "private_access_revoke" => "Revoke private access",
        "private_access_read" => "View private access",
        "node_start" => action_title(OperationKind::NodeStart),
        "node_stop" => action_title(OperationKind::NodeStop),
        "node_restart" => action_title(OperationKind::NodeRestart),
        "component_restart" => action_title(OperationKind::ComponentRestart),
        "component_logs" => action_title(OperationKind::ComponentLogs),
        "authentication_conformance" => action_title(OperationKind::AuthenticationConformance),
        "authentication_protected_spend" => {
            action_title(OperationKind::AuthenticationProtectedSpend)
        }
        "authentication_replay" => action_title(OperationKind::AuthenticationReplay),
        "component_forensics" => action_title(OperationKind::ComponentForensics),
        "private_transfer" => action_title(OperationKind::PrivateTransfer),
        "lab_recipe_bootstrap" => "Initialize recipe lab",
        "lab_recipe_route_channel_open" => "Open recipe route channels",
        "lab_recipe_fee_matrix_run" => "Run fee matrix",
        "liquidity_bootstrap" => action_title(OperationKind::BootstrapLiquidity),
        "peer_connect" => action_title(OperationKind::PeerConnect),
        "peer_disconnect" => action_title(OperationKind::PeerDisconnect),
        "channel_open" => action_title(OperationKind::ChannelOpen),
        "channel_policy_set" => action_title(OperationKind::ChannelPolicySet),
        "channel_close" => action_title(OperationKind::ChannelClose),
        "channel_force_close" => action_title(OperationKind::ChannelForceClose),
        "channel_rebalance" => action_title(OperationKind::ChannelRebalance),
        "network_partition" => action_title(OperationKind::NetworkPartition),
        "network_delay" => action_title(OperationKind::NetworkDelay),
        "network_loss" => action_title(OperationKind::NetworkLoss),
        "network_heal" => action_title(OperationKind::NetworkHeal),
        "wallet_initialize" => action_title(OperationKind::WalletInitialize),
        "wallet_balance" => action_title(OperationKind::WalletBalance),
        "wallet_fund" => action_title(OperationKind::WalletFund),
        "wallet_invoice" => action_title(OperationKind::WalletInvoice),
        "wallet_pay" => action_title(OperationKind::WalletPay),
        "wallet_quote_claim" => action_title(OperationKind::WalletQuoteClaim),
        "wallet_melt_quote_refresh" => action_title(OperationKind::WalletMeltQuoteRefresh),
        "wallet_round_trip" => action_title(OperationKind::WalletRoundTrip),
        "conservation_oracle" => action_title(OperationKind::ConservationOracle),
        "reachability_oracle" => action_title(OperationKind::ReachabilityOracle),
        "operation_status" => "Check operation status",
        "operation_wait" => "Wait for operation",
        "operation_wait_many" => "Wait for operations",
        "action_cancel" => "Cancel action",
        "action_list" => "List actions",
        "artifact_export" => "Export evidence",
        "evidence_section_read" => "View evidence section",
        "wallet_quote_status" => "Check wallet quote",
        "wallet_quote_list" => "List wallet quotes",
        "action_status" => "Check action status",
        _ => return None,
    })
}
